#include <iostream>
using namespace std;

class bee
{
public:
    string name;
    int age;
    char gender;
    char group;

    bee() {}; // Default constructor

    bee(string n, int a, char g, char gr) // Parameterized constructor
    {
        name = n;
        age = a;
        gender = g;
        group = gr;
    }

    bee(string n) // Parameterized constructor with only name
    {
        name = n;
    }

    bee(int a, string n, char g, char gr) // Parameterized constructor with different parameter order
    {
        name = n;
        age = a;
        gender = g;
        group = gr;
    }
};

int main()
{
    bee b1("Bumble", 3, 'M', 'A');
    cout << "Name: " << b1.name << endl;
    cout << "Age: " << b1.age << endl;
    cout << "Gender: " << b1.gender << endl;
    cout << "Group: " << b1.group << endl
         << endl;

    bee b2("Honey");
    cout << "Name: " << b2.name << endl
         << endl;

    bee b3(2, "Anuu", 'F', 'T');
    cout << "Name: " << b3.name << endl;
    cout << "Age: " << b3.age << endl;
    cout << "Gender: " << b3.gender << endl;
    cout << "Group: " << b3.group << endl << endl;

    bee b4 = b1;                            // Copy constructor generated by the compiler (HARD/DEEP COPY)
    cout << "Name: " << b4.name << endl;    // Means same value is copied to the new object but they are different objects in memory
    cout << "Age: " << b4.age << endl;
    cout << "Gender: " << b4.gender << endl;
    cout << "Group: " << b4.group << endl
         << endl;

    bee b5(b3);                          // Copy constructor generated by the compiler
    cout << "Name: " << b5.name << endl; // Passing an object as an argument to the constructor to create a new object with the same values
    cout << "Age: " << b5.age << endl;
    cout << "Gender: " << b5.gender << endl;
    cout << "Group: " << b5.group << endl
         << endl;

    return 0;
}